apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaos-robot-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: chaos-robot-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chaos-robot-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chaos-robot-role
subjects:
  - kind: ServiceAccount
    name: chaos-robot-sa

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: chaos-robot
spec:
  schedule: "*/5 * * * *"  
  concurrencyPolicy: Allow
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: chaos-robot-sa
          restartPolicy: Never
          containers:
            - name: chaos-robot
              image: bitnami/kubectl:latest   
              command:
                - /bin/sh
                - -c
                - |
                  echo "Chaos Robot: procurando 3 pods aleatórios a cada 5 minutos..."
                  
                  TARGETS=$(kubectl get pods -l run=php-apache -o name | awk 'BEGIN{srand()} {print rand() "\t" $0}' | sort -n | head -n 3 | cut -f2-)
                  
                  if [ -n "$TARGETS" ]; then
                    echo "Chaos Robot: Alvos selecionados:"
                    echo "$TARGETS"
                    
                    echo "$TARGETS" | xargs kubectl delete
                  else
                    echo "Chaos Robot: Nenhum pod encontrado."
                  fi
                  
                  echo "Chaos Robot: ciclo completo"
